// src/components/SnippetDetailController/SnippetDetailController.tsx
import * as React from "react";
import { Color } from "../../classes/Color";
import { ClickEventType } from "../../classes/Snippets/ClickEvent";
import { HoverEventType } from "../../classes/Snippets/HoverEvent";
import { KeybindSnippet } from "../../classes/Snippets/SnippetTypes/KeybindSnippet";
import { NBTSnippet } from "../../classes/Snippets/SnippetTypes/NBTSnippet";
import { ScoreboardObjectiveSnippet } from "../../classes/Snippets/SnippetTypes/ScoreboardObjectiveSnippet";
import { SelectorSnippet } from "../../classes/Snippets/SnippetTypes/SelectorSnippet";
import { Snippet } from "../../classes/Snippets/SnippetTypes/Snippet";
import { TextSnippet } from "../../classes/Snippets/SnippetTypes/TextSnippet";
import { CommandType, FeatureType, isFeatureAvailable } from "../../data/templates";
import { duplicate_snippet } from "../../helpers/copy_snippet";
import { formatSnippet } from "../../helpers/formatter";
import { Checkbox } from "../Forms/Checkbox";
import { MinecraftColorWell } from "../MinecraftColorWell";
import SnippetCollection from "../SnippetCollection";
import { GenericSnippetDetailController } from "./GenericDetailController";
import { KeybindSnippetDetailController } from "./KeybindSnippetDetailController";
import NBTSnippetController from "../InlineSnippetController/InlineNBTSnippetController";

export interface SnippetDetailControllerProps {
  commandType: CommandType
  snippet: Snippet
  updateSnippet: (snippet: Snippet) => void
  stopEditing: (save: boolean) => void
}

export interface SnippetDetailControllerState {
  
}

export class SnippetDetailController extends React.Component<SnippetDetailControllerProps, SnippetDetailControllerState> {
  
  constructor(props: SnippetDetailControllerProps) {
    super(props)
    
    console.log(this.props)

    this.state = {}

    this.changeColor = this.changeColor.bind(this)
    
    this.changeClickEventType = this.changeClickEventType.bind(this)
    this.changeClickEventValue = this.changeClickEventValue.bind(this)
    
    this.changeHoverEventType = this.changeHoverEventType.bind(this)
    this.changeHoverEventValue = this.changeHoverEventValue.bind(this)
    this.changeHoverEventChildren = this.changeHoverEventChildren.bind(this)
    this.changeInsertion = this.changeInsertion.bind(this)

    this.updateToggle = this.updateToggle.bind(this)
    this.updateField = this.updateField.bind(this)
    
    this.customAreaRender = this.customAreaRender.bind(this)
    this.clickEventRenderer = this.clickEventRenderer.bind(this)
    this.hoverEventRenderer = this.hoverEventRenderer.bind(this)
    this.hoverEventValueRender = this.hoverEventValueRender.bind(this)
    this.insertionRenderer = this.insertionRenderer.bind(this)
  }

  changeColor(event: any) {
    this.updateField("color", event.target.value)
  }

  changeClickEventType(event: any) {
    this.updateField("click_event_type", event.target.value)
  }

  changeClickEventValue(event: any) {
    this.updateField("click_event_value", event.target.value)
  }

  changeHoverEventType(event: any) {
    this.updateField("hover_event_type", event.target.value)
  }

  changeHoverEventValue(event: any) {
    this.updateField("hover_event_value", event.target.value)
  }

  changeHoverEventChildren(snippets: Array<Snippet>) {
    let newSnippet = duplicate_snippet(this.props.snippet)
    newSnippet.hover_event_children = snippets
    this.props.updateSnippet(newSnippet)
  }

  changeInsertion(event: any) {
    this.updateField("insertion", event.target.value)
  }

  updateToggle(field: string, event: any) {
    this.updateField(field, event.target.checked)
  }

  updateField(field: string, value: any) {
    let newSnippet = duplicate_snippet(this.props.snippet)
    newSnippet[field] = value
    this.props.updateSnippet(newSnippet)
  }

  customAreaRender() {
    if (this.props.snippet instanceof KeybindSnippet) {
      return <KeybindSnippetDetailController snippet={this.props.snippet} updateSnippet={this.props.updateSnippet} />
    } else if (this.props.snippet instanceof NBTSnippet) {
      return <NBTSnippetController snippet={this.props.snippet} updateSnippet={this.props.updateSnippet} />
    } else if (
         this.props.snippet instanceof ScoreboardObjectiveSnippet
      || this.props.snippet instanceof SelectorSnippet
      || this.props.snippet instanceof TextSnippet
    ) {
      return <GenericSnippetDetailController snippet={this.props.snippet} updateSnippet={this.props.updateSnippet} />
    } else {
      return <span>{typeof this.props.snippet} isn't implemented supported renderer</span>
    } 
  }

  clickEventRenderer() {
    if (!isFeatureAvailable(this.props.commandType, FeatureType.clicking)) {
      return null
    }

    return (
      <>
        <div className="row mb-2">
          <div className="col">
            <h4>Click Event:</h4>
          </div>
        </div>

        <div className="row mb-2">
          <div className="col-4">
            <select className="form-control" value={this.props.snippet.click_event_type} onChange={this.changeClickEventType}>
              <option key={ClickEventType.none} value={ClickEventType.none}>None</option>
              <option key={ClickEventType.open_url} value={ClickEventType.open_url}>Open URL</option>
              <option key={ClickEventType.run_command} value={ClickEventType.run_command}>Run Command</option>
              <option key={ClickEventType.suggest_command} value={ClickEventType.suggest_command}>Suggest Command</option>
              <option key={ClickEventType.change_page} value={ClickEventType.change_page}>Change Page (Books Only)</option>
              <option key={ClickEventType.copy_to_clipboard} value={ClickEventType.copy_to_clipboard}>Copy to Clipboard</option>
						</select>
          </div>
          {
            this.props.snippet.click_event_type !== ClickEventType.none ? (
              <div className="col">
                <input type="text" className="form-control" value={this.props.snippet.click_event_value} onChange={this.changeClickEventValue}/>
              </div>  
            ) : null
          }
        </div>
      </>
    )
  }

  hoverEventRenderer() {
    if (!isFeatureAvailable(this.props.commandType, FeatureType.hovering)) {
      return null
    }

    return (
      <>
        <div className="row mb-2">
          <div className="col">
            <h4>Hover Event:</h4>
          </div>
        </div>

        <div className="row mb-2">
          <div className="col-4">
            <select className="form-control" value={this.props.snippet.hover_event_type} onChange={this.changeHoverEventType}>
            <option key={HoverEventType.none} value={HoverEventType.none}>None</option>
            <option key={HoverEventType.show_entity} value={HoverEventType.show_entity}>Show Entity</option>
            <option key={HoverEventType.show_item} value={HoverEventType.show_item}>Show Item</option>
            <option key={HoverEventType.show_text} value={HoverEventType.show_text}>Show Text</option>
						</select>
          </div>
          { this.hoverEventValueRender() }
        </div>
      </>
    )
  }

  hoverEventValueRender() {
    if (this.props.snippet.hover_event_type == HoverEventType.show_text) {
      return (
        <div className="col">
          <div className="row">
            <div className="col inline-snippet-collection">
              <SnippetCollection commandType={CommandType.hovertext}
                                 snippets={this.props.snippet.hover_event_children}
                                 updateSnippets={this.changeHoverEventChildren}
                                 deleteAll={() => {
                                   this.changeHoverEventChildren([])
                                 }}
                                 />
            </div>
          </div>
        </div>
      )
    } else if (this.props.snippet.hover_event_type != HoverEventType.none) {
      return (
        <div className="col">
          <input type="text" className="form-control" value={this.props.snippet.hover_event_value} onChange={this.changeHoverEventValue}/>
        </div>
      )
    }
  }

  insertionRenderer() {
    if (!isFeatureAvailable(this.props.commandType, FeatureType.insertion)) {
      return null
    }

    return (
      <>
        <div className="row mb-2">
          <div className="col-4">
            <h4>Insertion:</h4>
          </div>
          <div className="col">
            <input className="form-control"
                   value={this.props.snippet.insertion}
                   onChange={this.changeInsertion} />
          </div>
        </div>
      </>
    )
  }

  render() {
    return (
      <>
        {/* <div className="row mb-2">
          <div className="col">
            <select className="form-control" onChange={this.changeSnippetType} value={this.props.snippet.type}>
              <option value={SnippetType.text}>Plain Text</option>
              <option value={SnippetType.selector}>Selector</option>
              <option value={SnippetType.scoreboardObjective}>Scoreboard Objective</option>
            </select>
          </div>
        </div> */}

        <div className="row mb-2">
          <div className="col">
            { this.customAreaRender() }
          </div>
          <div className="col-4">
            <div className="row mb-2">
              <div className="col">
                <select className="form-control" onChange={this.changeColor} value={this.props.snippet.color}>
                  {
                    Object.keys(Color).filter(key => !isNaN(Number(Color[key])))
                      .map(key => {
                        return <option key={Color[key]} value={Color[key]}>{key.split('_').map((s) => s.charAt(0).toUpperCase() + s.substring(1)).join(' ')}</option>
                      })
                  }
                </select>
              </div>
              <div className="col-3" style={{ display: "flex", flexDirection: "row-reverse" }}>
                <MinecraftColorWell color={this.props.snippet.color} />
              </div>
            </div>
            <div className="row">
              <div className="col">
                <Checkbox label="Bold" checked={this.props.snippet.bold} onChange={newValue => this.updateField("bold", newValue)} />
                <Checkbox label="Italic" checked={this.props.snippet.italic} onChange={newValue => this.updateField("italic", newValue)} />
                <Checkbox label="Underlined" checked={this.props.snippet.underlined} onChange={newValue => this.updateField("underlined", newValue)} />
                <Checkbox label="Strikethrough" checked={this.props.snippet.strikethrough} onChange={newValue => this.updateField("strikethrough", newValue)} />
                <Checkbox label="Obfuscated" checked={this.props.snippet.obfuscated} onChange={newValue => this.updateField("obfuscated", newValue)} />
              </div>
            </div>
          </div>
        </div>

        { this.clickEventRenderer() }

        { this.hoverEventRenderer() }
        
        { this.insertionRenderer() }

        <br />


        <hr />
        
        {/* Preview */}

        <div className="row mb-2">
          <div className="col">
            <h4>Preview:</h4>
          </div>
        </div>

        <div className="row mb-2">
          <div className="col">
            <p>
              { formatSnippet(this.props.snippet) }
            </p>
          </div>
        </div>

        {/* Exit Controls */}

        <div className="row">
          <div className="offset-8 col-2">
            <button className="btn btn-secondary btn-block" onClick={() => { this.props.stopEditing(false) }}>Cancel</button>
          </div>
          <div className="col-2">
            <button className="btn btn-primary btn-block" onClick={() => { this.props.stopEditing(true) }}>Save</button>
          </div>
        </div>
      </>
    )
  }
}

// src/components/SnippetControllers/DetailController/SnippetDetailController.svelte
<script lang="typescript">
  import { Button,Col,Row } from "sveltestrap";
  import type { Color } from "../../../classes/Color";
  import { getCSSHEX,minecraftColorSet } from "../../../classes/Color";
  import { ClickEventType } from "../../../classes/Snippets/ClickEvent";
  import { HoverEventType } from "../../../classes/Snippets/HoverEvent";
  import type { Snippet } from "../../../classes/Snippets/SnippetTypes/Snippet";
  import { CommandType,FeatureType,isFeatureAvailable } from "../../../data/templates";
  import { duplicate_snippet } from "../../../helpers/copy_snippet";
  import { customColors,version } from "../../../persistence/stores";
  import Checkbox from "../../generic/Checkbox.svelte";
  import MinecraftColorButton from "../../MinecraftColorButton.svelte";
  import SnippetCollection from "../../SnippetCollection.svelte";


  export let snippet: Snippet
  export let stopEditing: (save: boolean) => void
  export let colorManaging: boolean
  export let commandType: CommandType

  $: filteredColorSet = fullColorSet().filter((color) => { return color != "none" })
  $: clickEventTypeIsCommand = snippet.click_event_type == ClickEventType.run_command || snippet.click_event_type == ClickEventType.suggest_command

  function changeClickEventType(event: any) {
    updateField("click_event_type", event.target.value)
  }

  function changeClickEventValue(event: any) {
    updateField("click_event_value", event.target.value)
  }

  function changeHoverEventType(event: any) {
    updateField("hover_event_type", event.target.value)
  }

  function changeHoverEventValue(event: any) {
    updateField("hover_event_value", event.target.value)
  }

  function changeHoverEventChildren(snippets: Array<Snippet>) {
    let newSnippet = duplicate_snippet(snippet)
    newSnippet.hover_event_children = snippets
    snippet = newSnippet
  }

  function changeInsertion(event: any) {
    updateField("insertion", event.target.value)
  }

  function changeFont(event: any) {
    updateField("font", event.target.value)
  }

  function updateField(field: string, value: any) {
    let newSnippet = duplicate_snippet(snippet)
    newSnippet[field] = value
    snippet = newSnippet
  }

  function updateFontCheckbox(newValue: boolean) {
    let newSnippet = duplicate_snippet(snippet)
    if (newValue) {
      newSnippet.font = "minecraft:default"
    } else {
      newSnippet.font = null
    }
    snippet = newSnippet
  }

  function fullColorSet(): Color[] {
    return [...Object.keys(minecraftColorSet), ...$customColors]
  }

</script>

<div class="row mb-2">
  <div class="col">
    <!--
    {#if snippet instanceof NBTSnippet}
      <NbtSnippetController {snippet} {updateSnippet} {commandType} />
    {:else if
         snippet instanceof ScoreboardObjectiveSnippet
      || snippet instanceof SelectorSnippet
      || snippet instanceof TextSnippet
      || snippet instanceof KeybindSnippet
      || snippet instanceof TranslateSnippet
    }
      <GenericSnippetController {snippet} {updateSnippet} />
    {:else}
      <span>{typeof snippet} isn't implemented supported renderer</span>
    {/if}
    -->
    Unimplemented
  </div>
</div>
<hr />
<div class="row">
  <div class="col">
    <h4>
      Formatting Options:
    </h4>
  </div>
</div>
<div class="row">
  <div class="col-4">
    <div class="row mb-1">
      <div class="col">
        <span style="font-weight: bold">
          Preset Colors:
        </span>
      </div>
    </div>
    <div class="row mb-2">
      <div class="col d-flex flex-wrap">
        {#each filteredColorSet as color}
          <MinecraftColorButton
            {color}
            checked={snippet.color == color}
            onClick={(newColor) => {
              updateField("color", newColor)
            }}
          />
        {/each}
      </div>
    </div>
    {#if isFeatureAvailable(commandType, $version, FeatureType.customColor)}
      <div class="row mb-1">
        <div class="col">
          <span style="font-weight: bold;">
            Custom Color:
          </span>
          <input
            type="color"
            value={getCSSHEX(snippet.color)}
            on:input={(evt) => {
              updateField("color", evt.currentTarget.value.toUpperCase())
            }}
          />
        </div>
      </div>
      <!-- <div class="row mb-1">
        <div class="col">
          <button onClick={() => { props.setColorManaging(true) }}>Color Manager...</button>
        </div>
      </div> -->
    {/if}
    <div class="row mb-2">
      <Col>
        {#if snippet.color != "none"}
          <Button
            color="secondary"
            on:click={() => {
              updateField("color", "none")
            }}
          >
            Unset Color
          </Button>
        {:else}
          <p class="mb-0">
            No color is selected, so it will appear
            the default color in-game, usually white or black.
          </p>
        {/if}
      </Col>
    </div>
  </div>
  <div class="col-4">
    <Checkbox checked={snippet.bold} on:change={event => updateField("bold", event.detail)}>
      Bold
    </Checkbox>
    <Checkbox checked={snippet.italic} on:change={event => updateField("italic", event.detail)}>
      Italic
    </Checkbox>
    <Checkbox checked={snippet.underlined} on:change={event => updateField("underlined", event.detail)}>
      Underlined
    </Checkbox>
    <Checkbox checked={snippet.strikethrough} on:change={event => updateField("strikethrough", event.detail)}>
      Strikethrough
    </Checkbox>
    <Checkbox checked={snippet.obfuscated} on:change={event => updateField("obfuscated", event.detail)}>
      Obfuscated
    </Checkbox>
  </div>
  {#if isFeatureAvailable(commandType, $version, FeatureType.font)}
    <div class="col-4">
      <div class="row">
        <div class="col">
          <Checkbox checked={snippet.font !== null} on:change={event => { updateFontCheckbox(event.detail) }}>
            Custom Font
          </Checkbox>
        </div>
      </div>
      <div class="row">
        <div class="col">
          {#if snippet.font !== null}
            <input type="text" class="form-control" value={snippet.font} on:input={changeFont}/>
          {/if}
        </div>
      </div>
    </div>
  {/if}
</div>
<hr />

{#if isFeatureAvailable(commandType, $version, FeatureType.clicking)}
  <div class="row">
    <div class="col">
      <h4>Click Event:</h4>
    </div>
  </div>

  <Row class="mb-2">
    <div class="col-4">
      <select class="custom-select" value={snippet.click_event_type} on:input={changeClickEventType}>
        <option selected={snippet.click_event_type == ClickEventType.none} value={ClickEventType.none}>
          None
        </option>
        <option selected={snippet.click_event_type == ClickEventType.open_url} value={ClickEventType.open_url}>
          Open URL
        </option>
        <option selected={snippet.click_event_type == ClickEventType.run_command} value={ClickEventType.run_command}>
          Run Command
        </option>
        <option selected={snippet.click_event_type == ClickEventType.suggest_command} value={ClickEventType.suggest_command}>
          Suggest Command
        </option>
        <option selected={snippet.click_event_type == ClickEventType.change_page} value={ClickEventType.change_page}>
          Change Page (Books Only)
        </option>
        <option selected={snippet.click_event_type == ClickEventType.copy_to_clipboard} value={ClickEventType.copy_to_clipboard}>
          Copy to Clipboard
        </option>
      </select>
    </div>
    {#if snippet.click_event_type != ClickEventType.none}
      <div class="col">
        <div class="row">
          <div class="col">
            <input
              list={clickEventTypeIsCommand ? "datalist-commands" : null}
              type="text"
              class="form-control"
              value={snippet.click_event_value}
              on:input={changeClickEventValue}
            />
          </div>  
        </div>
        {#if commandType == CommandType.sign}
          <div class="row mt-2">
            <div class="col">
              <div class="alert alert-warning" role="alert">
                If you have more than one text entry for each line
                in the sign, the click event will not be applied.
                This is due to Minecraft limitations with signs.
              </div>
            </div>
          </div>
        {/if}
      </div>
    {/if}
  </Row>
  <hr />
{/if}

{#if isFeatureAvailable(commandType, $version, FeatureType.hovering)}
  <div class="row">
    <div class="col">
      <h4>Hover Event:</h4>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-4">
      <select class="custom-select" value={snippet.hover_event_type} on:input={changeHoverEventType}>
        <option selected={snippet.hover_event_type == HoverEventType.none} value={HoverEventType.none}>
          None
        </option>
        <option selected={snippet.hover_event_type == HoverEventType.show_entity} value={HoverEventType.show_entity}>
          Show Entity
        </option>
        <option selected={snippet.hover_event_type == HoverEventType.show_item} value={HoverEventType.show_item}>
          Show Item
        </option>
        <option selected={snippet.hover_event_type == HoverEventType.show_text} value={HoverEventType.show_text}>
          Show Text
        </option>
      </select>
    </div>
    {#if snippet.hover_event_type == HoverEventType.show_text}
      <div class="col">
        <div class="row">
          <div class="col inline-snippet-collection">
            <SnippetCollection
              commandType={CommandType.hovertext}
              snippets={snippet.hover_event_children}
              updateSnippets={changeHoverEventChildren}
              deleteAll={() => {
                changeHoverEventChildren([])
              }}
              bind:colorManaging={colorManaging}
            />
          </div>
        </div>
      </div>
    {:else if snippet.hover_event_type != HoverEventType.none}
      <div class="col">
        <input type="text" class="form-control" value={snippet.hover_event_value} onChange={changeHoverEventValue}/>
      </div>
    {/if}
  </div>
  <hr />
{/if}

{#if isFeatureAvailable(commandType, $version, FeatureType.insertion)}
  <div class="row mb-2">
    <div class="col-4">
      <h4>Insertion:</h4>
    </div>
    <div class="col">
      <input
        class="form-control"
        value={snippet.insertion}
        on:input={changeInsertion}
      />
    </div>
  </div>
  <hr />
{/if}

<br />

<!-- Preview -->

<div class="row mb-2">
  <div class="col">
    <h4>Preview:</h4>
  </div>
</div>

<div class="row mb-2">
  <div class="col">
    <p>
      <!--{ formatSnippet(props.snippet) }-->
    </p>
  </div>
</div>

<!-- Exit Controls -->

<div class="row">
  <div class="offset-8 col-2">
    <button class="btn btn-secondary btn-block" on:click={() => { stopEditing(false) }}>Cancel</button>
  </div>
  <div class="col-2">
    <button class="btn btn-primary btn-block" on:click={() => { stopEditing(true) }}>Save</button>
  </div>
</div>
