// src/components/SnippetControllers/GenericSnippetController.svelte
<script lang="typescript">
  import { Button,Col,Row } from "sveltestrap";
  import type { FieldSpecifier,Snippet } from "../../classes/Snippets/SnippetTypes/Snippet";
  import type { TextSnippet } from "../../classes/Snippets/SnippetTypes/TextSnippet";
  import PlusCircle from "../generic/Icons/PlusCircle.svelte";
  import TimesCircle from "../generic/Icons/TimesCircle.svelte";

  export let snippet: TextSnippet
  export let updateSnippet: (snippet: Snippet) => void

  function updateField(field: FieldSpecifier, value: any, index: number | null = null) {
    let newSnippet = snippet.copy()
    if (field.fieldType == "string") {
      newSnippet[field.field] = value
    } else if (field.fieldType == "string[]") {
      newSnippet[field.field][index] = value
    } else {
      console.error("Unexpected fieldType", field.fieldType)
    }
    updateSnippet(newSnippet)
  }

  function extendArray(field: FieldSpecifier) {
    let newSnippet = snippet.copy()
    newSnippet[field.field].push("")
    updateSnippet(newSnippet)
  }

  function removeIndex(field: FieldSpecifier, index: number) {
    let newSnippet = snippet.copy()
    newSnippet[field.field].splice(index, 1)
    updateSnippet(newSnippet)
  }

</script>

<Row>
  {#each snippet.editor_fields() as field, index}
    {#if field.fieldType == "string"}
      <div class="col-6">
        <input
          list={field.datalistID}
          class="form-control"
          placeholder={field.placeholder}
          value={snippet[field.field]}
          on:input={(evt) => { updateField(field, evt.currentTarget.value) }}
        />
      </div>
    {:else if field.fieldType == "string[]"}
      <!-- let stringList: string[] = snippet[field.field]; -->
      <div class="col-6">
        {#each snippet.value(field) as value, subIndex}
          <Row class="mb-1">
            <Col>
              <input
                list={field.datalistID}
                class="form-control"
                placeholder={`${field.placeholder} #${subIndex + 1}`}
                value={value}
                on:input={(evt) => {
                  updateField(field, evt.currentTarget.value, subIndex)
                }}
              />
            </Col>
            <div class="col-3">
              <Button
                color="danger"
                on:click={() => { removeIndex(field, subIndex) }}
              >
                <TimesCircle />
              </Button>
            </div>
          </Row>
        {/each}
        <Row>
          <Col>
            <Button color="success" on:click={() => { extendArray(field) }}>
              <PlusCircle />
              Add Parameter Value
            </Button>
          </Col>
        </Row>
      </div>
    {/if}
  {/each}
</Row>

// src/components/SnippetControllers/GenericSnippetController.tsx
import * as React from "react";
import { KeybindSnippet } from "../../classes/Snippets/SnippetTypes/KeybindSnippet";
import { NBTSnippet } from "../../classes/Snippets/SnippetTypes/NBTSnippet";
import { ScoreboardObjectiveSnippet } from "../../classes/Snippets/SnippetTypes/ScoreboardObjectiveSnippet";
import { SelectorSnippet } from "../../classes/Snippets/SnippetTypes/SelectorSnippet";
import { FieldSpecifier, Snippet } from "../../classes/Snippets/SnippetTypes/Snippet";
import { TextSnippet } from "../../classes/Snippets/SnippetTypes/TextSnippet";
import { TranslateSnippet } from "../../classes/Snippets/SnippetTypes/TranslateSnippet";
import Button from "../generic/Button";

export type GenericFieldCompatable = ScoreboardObjectiveSnippet | NBTSnippet | KeybindSnippet | SelectorSnippet | TextSnippet | TranslateSnippet

export interface GenericSnippetControllerProps {
  snippet: GenericFieldCompatable
  updateSnippet: (snippet: Snippet) => void
}

export const GenericSnippetController: React.FunctionComponent<GenericSnippetControllerProps> = ({ snippet, updateSnippet }) => {

  function updateField(field: FieldSpecifier, event: any, index: number | null = null) {
    let newSnippet = snippet.copy()
    if (field.fieldType == "string") {
      newSnippet[field.field] = event.target.value
    } else if (field.fieldType == "string[]") {
      newSnippet[field.field][index] = event.target.value
    } else {
      console.error("Unexpected fieldType", field.fieldType)
    }
    updateSnippet(newSnippet)
  }
  
  function extendArray(field: FieldSpecifier) {
    let newSnippet = snippet.copy()
    newSnippet[field.field].push("")
    updateSnippet(newSnippet)
  }

  function removeIndex(field: FieldSpecifier, index: number) {
    let newSnippet = snippet.copy()
    newSnippet[field.field].splice(index, 1)
    updateSnippet(newSnippet)
  }

  return (
    <div className="row">
      {
        snippet.editor_fields().map((field, index) => {
          if (field.fieldType == "string") {
            return (
              <div className="col-6" key={index}>
                <input
                  list={field.datalistID}
                  className="form-control"
                  placeholder={field.placeholder}
                  value={snippet[field.field]}
                  onChange={(evt) => { updateField(field, evt) }}
                />
              </div>
            )
          } else if (field.fieldType == "string[]") {
            console.log("Working with field", field)
            console.log("On snippet...", snippet)
            let stringList: string[] = snippet[field.field];
            console.log(stringList);
            return (
              <div className="col-6" key={index}>
                {
                  snippet[field.field].map((value: string, subIndex: number) => {
                    return (
                      <div className="row mb-1" key={`${index}-${subIndex}`}>
                        <div className="col">
                          <input
                            list={field.datalistID}
                            className="form-control"
                            placeholder={`${field.placeholder} #${subIndex + 1}`}
                            value={value}
                            onChange={(evt) => { updateField(field, evt, subIndex) }}
                          />
                        </div>
                        <div className="col-3">
                          <Button
                            type="danger"
                            icon="times-circle"
                            onClick={() => { removeIndex(field, subIndex) }}
                          />
                        </div>
                      </div>
                    )
                  })
                }
                <div className="row">
                  <div className="col">                   
                    <Button
                      type="success"
                      icon="plus-circle"
                      onClick={() => { extendArray(field) }}
                    >
                      Add Parameter Value
                    </Button>
                  </div>
                </div>
              </div>
            )
          }
        })
      }
    </div>
  )
}
