// src/components/InlineSnippetController/InlineSnippetController.tsx
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import * as React from "react";
import { DraggableProvided } from "react-beautiful-dnd";
import { KeybindSnippet } from "../../classes/Snippets/SnippetTypes/KeybindSnippet";
import { LinebreakSnippet } from "../../classes/Snippets/SnippetTypes/LinebreakSnippet";
import { NBTSnippet } from "../../classes/Snippets/SnippetTypes/NBTSnippet";
import { PagebreakSnippet } from "../../classes/Snippets/SnippetTypes/PagebreakSnippet";
import { ScoreboardObjectiveSnippet } from "../../classes/Snippets/SnippetTypes/ScoreboardObjectiveSnippet";
import { SelectorSnippet } from "../../classes/Snippets/SnippetTypes/SelectorSnippet";
import { Snippet } from "../../classes/Snippets/SnippetTypes/Snippet";
import { TextSnippet } from "../../classes/Snippets/SnippetTypes/TextSnippet";
import { MinecraftColorWell } from "../MinecraftColorWell";
import InlineEditButton, { InlineEditButtonAction } from "./InlineEditButton";
import { InlineGenericSnippetController } from "./InlineGenericSnippetController";
import InlineNBTSnippetController from "./InlineNBTSnippetController";

export interface InlineSnippetControllerProps {
  snippet: Snippet
  updateSnippet: (Snippet) => void
  startEditingSnippet: (Snippet) => void
  removeSnippet: (Snippet) => void
  duplicateSnippet: (Snippet) => void

  provided: DraggableProvided
}

export class InlineSnippetController extends React.Component<InlineSnippetControllerProps, {}> {
  
  constructor(props: InlineSnippetControllerProps) {
    super(props)
    
    this.editButtonClick = this.editButtonClick.bind(this)
    this.customController = this.customController.bind(this)
  }
  
  editButtonClick(action: string) {
    if (action == "start-editing") {
      this.props.startEditingSnippet(this.props.snippet)
    } else if (action == "delete") {
      this.props.removeSnippet(this.props.snippet)
    } else if (action == "duplicate") {
      this.props.duplicateSnippet(this.props.snippet)
    } else {
      alert(`Failed to catch ${action}`)
    }
  }
  
  customController() {
    if (this.props.snippet instanceof LinebreakSnippet) {
      return <span>Line Break ⏎</span>
    } else if (this.props.snippet instanceof PagebreakSnippet) {
      return <span>Page Break <FontAwesomeIcon icon="file-alt" /></span>
    } else if (this.props.snippet instanceof NBTSnippet) {
      return <InlineNBTSnippetController snippet={this.props.snippet} updateSnippet={this.props.updateSnippet} />
    } else if (
         this.props.snippet instanceof ScoreboardObjectiveSnippet
      || this.props.snippet instanceof KeybindSnippet
      || this.props.snippet instanceof SelectorSnippet
      || this.props.snippet instanceof TextSnippet
    ) {
      return <InlineGenericSnippetController snippet={this.props.snippet} updateSnippet={this.props.updateSnippet} />
    } else {
      return <span>{typeof this.props.snippet} isn't implemented</span>
    }
  }
  
  render() {
    const editingEnabled = !(this.props.snippet instanceof LinebreakSnippet
      || this.props.snippet instanceof PagebreakSnippet)
    let startEditingAction: InlineEditButtonAction = {
      id: "start-editing",
      text: "Edit",
      enabled: editingEnabled
    }

    let deleteAction: InlineEditButtonAction = {
      id: "delete",
      text: "Delete",
      icon: "trash-alt",
      enabled: true
    }

    let duplicateAction: InlineEditButtonAction = {
      id: "duplicate",
      text: "Duplicate",
      icon: "clone",
      enabled: true
    }
    
    const { provided } = this.props;

    return (
      <div className="row mb-2" {...provided.draggableProps} {...provided.dragHandleProps} ref={provided.innerRef}>
        <div className="col-4 col-md-3 col-lg-2 d-flex flex-column justify-content-center">
          <InlineEditButton onClick={this.editButtonClick}
                            mainAction={startEditingAction}
                            dropdownActions={[
                              deleteAction,
                              duplicateAction
                            ]} />
        </div>
        
        {/*
        Flex justification is for text fields
        which are used for page and linebreaks
        */}
        <div className="col"
             style={{
               display: "flex",
               flexDirection: "column",
               justifyContent: "center"
             }}>
          { this.customController() }
        </div>
        
        <div className="col-1">
          <MinecraftColorWell color={this.props.snippet.color} />
        </div>
      </div>
    )
  }
}

// src/components/SnippetControllers/InlineSnippetController.svelte
<script lang="typescript">
  import { Col,Row } from "sveltestrap";
  import { genericSnippet } from "../../classes/Snippets/SnippetTypes/GenericFieldCompatable";
  import { LinebreakSnippet } from "../../classes/Snippets/SnippetTypes/LinebreakSnippet";
  import { GroupSnippet } from "../../classes/Snippets/SnippetTypes/GroupSnippet";
  import { NBTSnippet } from "../../classes/Snippets/SnippetTypes/NBTSnippet";
  import { PagebreakSnippet } from "../../classes/Snippets/SnippetTypes/PagebreakSnippet";
  import type { Snippet } from "../../classes/Snippets/SnippetTypes/Snippet";
  import { TranslateSnippet } from "../../classes/Snippets/SnippetTypes/TranslateSnippet";
  import Clone from "../generic/Icons/Clone.svelte";
  import Edit from "../generic/Icons/Edit.svelte";
  import FileAlt from "../generic/Icons/FileAlt.svelte";
  import TrashAlt from "../generic/Icons/TrashAlt.svelte";
  import SplitDropdown from "../generic/SplitDropdown.svelte";
  import MinecraftColorWell from "../MinecraftColorWell.svelte";
  import GenericSnippetController from "./GenericSnippetController.svelte";
  import NBTSnippetController from "./NBTSnippetController.svelte";

  export let snippet: Snippet
  export let editing: Snippet
  export let updateSnippet: (snippet: Snippet) => void
  export let removeSnippet: (snippet: Snippet) => void
  export let duplicateSnippet: (snippet: Snippet) => void

  function startEditingSnippet() {
    editing = snippet
  }

  $: editingEnabled = !(snippet instanceof LinebreakSnippet || snippet instanceof PagebreakSnippet)
</script>

<Row class="mb-2">
  <div class="col-4 col-md-3 col-lg-2 d-flex flex-column justify-content-center">
    <SplitDropdown
      color="secondary"
      disabled={!editingEnabled}
      block
      on:click={() => { startEditingSnippet() }}
      dropdowns={[
        {
          label: "Delete",
          icon: TrashAlt,
          onClick: () => {
            removeSnippet(snippet)
          }
        },
        {
          label: "Duplicate",
          icon: Clone,
          onClick: () => {
            duplicateSnippet(snippet)
          }
        }
      ]}
    >
      <Edit />
      Edit
    </SplitDropdown>
  </div>

  <!--
      Flex justification is for text fields
      which are used for page and linebreaks
    -->
  <Col style="display: flex; flex-direction: column; justify-content: center;">
    {#if snippet instanceof LinebreakSnippet}
      <span>Line Break ⏎</span>
    {:else if snippet instanceof PagebreakSnippet}
      <span>Page Break <FileAlt /></span>
    {:else if snippet instanceof NBTSnippet}
      <NBTSnippetController {snippet} {updateSnippet} />
    {:else if snippet instanceof TranslateSnippet}
      <span>Translation Snippet ({ snippet.translate }) - Click Edit to modify</span>
    {:else if snippet instanceof GroupSnippet}
      <span>group</span>
    {:else if genericSnippet(snippet)}
      <!-- Generic Snippet will be nil if it's not a generic snippet -->
      <!-- by if-ing first, can assure it's not null -->
      <GenericSnippetController snippet={genericSnippet(snippet)} {updateSnippet} />
    {:else}
      <span>{typeof snippet} isn't implemented :(S</span>
    {/if}
  </Col>

  <div class="col-1">
    <MinecraftColorWell color={snippet.color} />
  </div>
</Row>
