// src/components/SnippetControllers/NBTSnippetController.svelte
<script lang="ts">
  import { Col,Row } from "sveltestrap";
  import { NBTSnippet,NBTType } from "../../classes/Snippets/SnippetTypes/NBTSnippet";
  import type { Snippet } from "../../classes/Snippets/SnippetTypes/Snippet";
  import { FeatureType,isFeatureAvailable } from "../../data/templates";
  import { commandType,version } from "../../persistence/stores";
  import Checkbox from "../generic/Checkbox.svelte";


  export let snippet: NBTSnippet
  export let updateSnippet: (snippet: Snippet) => void

  function updateField(field: string, event: any) {
    updateFieldValue(field, event.target.value)
  }

  function updateFieldValue(field: string, value: any) {
    let newSnippet = snippet.copy()
    newSnippet[field] = value
    updateSnippet(newSnippet)
  }

  function changeNBTType(event: any) {
    let newSnippet = snippet.copy()
    newSnippet.type = event.target.value
    updateSnippet(newSnippet)
  }
</script>

{#if (!isFeatureAvailable($commandType, $version, FeatureType.nbtComponent))}
  <Row>
    <Col>
      <p>NBT Components require Minecraft 1.14+</p>
    </Col>
  </Row>
{:else}
  <Row class="mb-2">
    <Col>
      <select class="custom-select" value={snippet.type} on:input={changeNBTType}>
        <option value={NBTType.storage} disabled={!isFeatureAvailable($commandType, $version, FeatureType.nbtStorageComponent)}>
          Storage
          {#if !isFeatureAvailable($commandType, $version, FeatureType.nbtStorageComponent)}
            {" (Requires 1.15+)"}
          {/if}
        </option>
        <option value={NBTType.entity}>Entity</option>
        <option value={NBTType.block}>Block</option>
      </select>
    </Col>
    <Col>
      <input class="form-control" value={snippet.storage} placeholder="Identifier" on:change={(evt) => { updateField("storage", evt) }} />
    </Col>
  </Row>
  <Row>
    <Col>
      <input class="form-control" value={snippet.nbt} placeholder="NBT Path" on:input={(evt) => { updateField("nbt", evt) }} />
    </Col>
  </Row>
  <Row>
    <Col>
      <Checkbox checked={snippet.interpret} on:change={(event) => { updateFieldValue("interpret", event.detail) }}>
        Interpret
      </Checkbox>
    </Col>
  </Row>
{/if}

// src/components/SnippetControllers/NBTSnippetController.tsx
import * as React from "react";
import { NBTSnippet, NBTType } from "../../classes/Snippets/SnippetTypes/NBTSnippet";
import { CommandType, FeatureType, isFeatureAvailable } from "../../data/templates";
import { Version } from "../../helpers/versions";
import { Checkbox } from "../Forms/Checkbox";

export interface NBTSnippetControllerProps {
  snippet: NBTSnippet
  updateSnippet: (Snippet) => void
  commandType: CommandType
  version: Version
}

export const NBTSnippetController: React.FunctionComponent<NBTSnippetControllerProps> = (props) => {

  function updateField(field: string, event: any) {
    updateFieldValue(field, event.target.value)
  }

  function updateFieldValue(field: string, value: any) {
    let newSnippet = props.snippet.copy()
    newSnippet[field] = value
    props.updateSnippet(newSnippet)
  }

  function changeNBTType(event: any) {
    let newSnippet = props.snippet.copy()
    newSnippet.type = event.target.value
    props.updateSnippet(newSnippet)
  }

  if (!isFeatureAvailable(props.commandType, props.version, FeatureType.nbtComponent)) {
    return (
      <div className="row">
        <div className="col">
          <p>NBT Components require Minecraft 1.14+</p>
        </div>
      </div>
    )
  }

  return (
    <>
      <div className="row mb-2">
        <div className="col">
          <select className="custom-select" value={props.snippet.type} onChange={changeNBTType}>
            <option key={NBTType.storage} value={NBTType.storage} disabled={!isFeatureAvailable(props.commandType, props.version, FeatureType.nbtStorageComponent)}>
              Storage
              {
                isFeatureAvailable(props.commandType, props.version, FeatureType.nbtStorageComponent) ? null : (
                  " (Requires 1.15+)"
                )
              }
            </option>
            <option key={NBTType.entity} value={NBTType.entity}>Entity</option>
            <option key={NBTType.block} value={NBTType.block}>Block</option>
          </select>
        </div>
        <div className="col">
          <input className="form-control" value={props.snippet.storage} placeholder="Identifier" onChange={(evt) => { updateField("storage", evt) }} />
        </div>
      </div>
      <div className="row">
        <div className="col">
          <input className="form-control" value={props.snippet.nbt} placeholder="NBT Path" onChange={(evt) => { updateField("nbt", evt) }} />
        </div>
      </div>
      <div className="row">
        <div className="col">
          <Checkbox checked={props.snippet.interpret} onChange={(newValue) => { updateFieldValue("interpret", newValue) }} label="Interpret" />
        </div>
      </div>
    </>
  )
}
