// src/components/Tellraw.tsx
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import * as React from "react";
import { LSKEY_COMMAND_STRING, LSKEY_COMMAND_TYPE, LSKEY_SNIPPET_ARR, VERSION } from "../constants";
import { CommandType, template_lookup } from "../data/templates";
import { compile } from "../helpers/compile";
import { export_snippets } from "../helpers/export";
import { loadV4State, loadV5State, mapV4Template } from "../helpers/loaders";
import { useLocalStorage, useLSSnippets } from "../helpers/useLocalStorage";
import CommandTemplatesController from "./CommandTemplatesController";
import Importing from "./Importing";
import Preview from "./Preview";
import SnippetCollection from "./SnippetCollection";
import Button from "./generic/Button";

const Tellraw: React.FunctionComponent<{}> = () => {  
  let [snippets, setSnippets] = useLSSnippets(LSKEY_SNIPPET_ARR, [])
  let [commandType, setCommandType] = useLocalStorage(LSKEY_COMMAND_TYPE, CommandType.tellraw)
  let [command, setCommand] = useLocalStorage(LSKEY_COMMAND_STRING, template_lookup(commandType)[0])

  let [exporting, setExporting] = React.useState(false)

  let [importing, setImporting] = React.useState(false)

  const compiled = compile(snippets, command, commandType)

  function updateCustomCommand(event: any) {
    setCommand(event.target.value)
  }

  function updateCommandType(type: CommandType, command_override?: string) {
    setCommandType(type)
    setCommand(command_override || template_lookup(type)[0])
  }

  function startImporting() {
    setImporting(true)
  }

  function stopImporting() {
    setImporting(false)
  }

  if (importing) {
    return <Importing setSnippets={setSnippets} setCommand={setCommand} setCommandType={setCommandType} stopImporting={stopImporting} />
  }

  if (exporting) {
    return (
      <div className="container">
        <div className="row">
          <div className="col-md-6 offset-md-3 light-well" style={{ textAlign: "center" }}>
            <p className="mb-3">
              Click below to copy the exported command string. Store it in a safe place
              to import back onto the site in the future.
            </p>
            <textarea readOnly={true}
                      className="form-control mb-3"
                      onClick={(event) => {
                        event.currentTarget.select()
                      }}
                      value={ export_snippets(snippets, command, commandType) } />
            <Button type="success" icon="check-circle" onClick={() => { setExporting(false) }}>Done</Button>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="container">
      <div className="row">
        <div className="col-sm-8 col-md mb-2">
          <h4>Tellraw Generator for Minecraft</h4>
        </div>
        <div className="col-sm-5 mb-2">
          <div className="btn-toolbar d-flex justify-content-end"
                role="toolbar"
                aria-label="Toolbar with button groups">
            <a className="btn btn-danger btn-sm"
              href="https://github.com/ezfe/tellraw/issues/new"
              target="_">
              <FontAwesomeIcon icon="exclamation-triangle" /> Report an Issue
            </a>
            <div className="btn-group ml-2">
              <button className="btn btn-secondary btn-sm dropdown-toggle"
                      type="button"
                      id="dropdownMenuButton"
                      data-toggle="dropdown"
                      aria-haspopup="true"
                      aria-expanded="false"
                      area-label="Miscellaneous Actions">
                <FontAwesomeIcon icon="list" />
              </button>
              <div className="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a className="dropdown-item" href="https://twitter.com/intent/tweet?original_referer=http%3A%2F%2Fwww.minecraftjson.com%2F&text=%2Ftellraw%20generator%20for%20minecraft&tw_p=tweetbutton&url=http%3A%2F%2Fwww.minecraftjson.com%2F&via=superezfe">
                  <FontAwesomeIcon icon={["fab", "twitter"]} /> Tweet
                </a>
                <a className="dropdown-item" href="https://status.minecraftjson.com">
                  <FontAwesomeIcon icon="wifi" /> Uptime
                </a>
                <a className="dropdown-item" href="https://github.com/ezfe/tellraw/archive/master.zip">
                  <FontAwesomeIcon icon="file-download" /> Download Website
                </a>
                <a className="dropdown-item" href="https://legacy.minecraftjson.com">
                  <FontAwesomeIcon icon="code-branch" /> Legacy Version
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="row">
        <div className="col-sm-5 col-md-3 mb-2">
          <span style={{ fontWeight: "bold" }}>Player and Command</span>
          <br />
          <span>Used to select and execute different players</span>
        </div>
        <div className="col-sm mb-4">
          <input value={command}
                 onChange={updateCustomCommand}
                 type="text"
                 className="form-control" />
        </div>
      </div>

      <CommandTemplatesController commandType={commandType}
                                  updateCommandType={updateCommandType} />
      
      <SnippetCollection commandType={commandType}
                          snippets={snippets} 
                          updateSnippets={(snippets) => {
                            setSnippets(snippets)
                          }}
                          deleteAll={() => {
                            setSnippets([])
                            setCommand(template_lookup(CommandType.tellraw)[0])
                            setCommandType(CommandType.tellraw)
                          }} />
      
      <br />
      <br />
      <div className="row mb-2">
        <div className="col-2">
          <span style={{}}>Command</span>
        </div>
        <div className="col">
          <textarea readOnly={true}
                    className="form-control"
                    onClick={(event) => {
                      event.currentTarget.select()
                    }}
                    value={compiled} />
        </div>
      </div>
      <div className="row">
        <div className="col-sm-2 offset-sm-2 mb-2">
          <Button type="light"
                  className="btn-block"
                  onClick={startImporting}
                  icon="file-import">
            Import
          </Button>
        </div>
        <div className="col-sm-2 mb-2">
          <Button type="light"
                  className="btn-block"
                  onClick={() => { setExporting(true) }}
                  icon="file-export">
            Export
          </Button>
        </div>
      </div>

      <Preview snippets={snippets} commandType={commandType} />

      <hr />

      <div className="row">
        <div className="col">
          <span style={{ color: "grey", fontSize: "10px" }}>
            <a href="https://ezekielelin.com/contact" target="_blank">Contact Me</a> | "Minecraft" content and materials are trademarks and copyrights of Mojang and its licensors. This site is not affiliated with Mojang.
			    </span>
        </div>
      </div>
    </div>
  )
}

export default Tellraw

// src/lib/components/Tellraw.svelte
<script lang="ts">
	import { Button,Row } from 'sveltestrap';
	import { TextSnippet } from '../classes/Snippets/SnippetTypes/TextSnippet';
	import { CommandType,FeatureType,isFeatureAvailable,template_lookup } from '../data/templates';
	import { compile } from '../helpers/compile';
	import { export_snippets } from '../helpers/export';
	import type { TranslationSet } from '../helpers/translation_processor';
	import { command,commandType,customColors,customLanguageTranslations,litSign,snippets,version } from '../persistence/stores';
	import SiteActions from './buttons/SiteActions.svelte';
	import CommandTemplatesController from './CommandTemplatesController.svelte';
	import ArrayDatalist from './Datalist/ArrayDatalist.svelte';
	import DictionaryDatalist from './Datalist/DictionaryDatalist.svelte';
	import CheckCircle from './generic/Icons/CheckCircle.svelte';
	import ExclamationTriangle from './generic/Icons/ExclamationTriangle.svelte';
	import FileExport from './generic/Icons/FileExport.svelte';
	import FileImport from './generic/Icons/FileImport.svelte';
	import LightWell from './generic/LightWell.svelte';
	import Importing from './Importing.svelte';
	import PreviewContainer from './Previews/PreviewContainer.svelte';
	import Settings from './Settings.svelte';
	import SnippetCollection from './SnippetCollection.svelte';

	let exporting = false;
	let importing = false;

	let colorManaging = false;
	let hideWrapper = false;

	let translationSet: TranslationSet = {};

	$: compiled = compile($snippets, $command, $commandType, $version, $litSign);

	function clearAllSnippets() {
		const titleString = "Are you sure!?!"
		const bodyString = "Clicking Delete will remove all your text and reset it to an empty string."
		if (confirm(`${titleString}\n${bodyString}`)) {
			snippets.set([])
			commandType.set(CommandType.tellraw)
			command.set(template_lookup($commandType)[0])
		}
	}

	function startImporting() {
		importing = true
	}

	function startExporting() {
		exporting = true
	}

	function updateTranslationSet(newContents: any) {
		if (newContents.constructor == Object) {
			translationSet = newContents;
		} else {
			console.error('Received non-object translation set', newContents);
		}
	}

	function speedtest() {
		let arr = [];
		for (var i = 0; i < 10000; i++) {
			arr.push(new TextSnippet(null));
		}
		snippets.set(arr);
	}
</script>

<div class="container">
	{#if importing}
		<Importing bind:importing={importing} />
	{:else if exporting}
		<Row>
			<div class="col-md-6 offset-md-3 text-center">
				<LightWell>
					<p class="mb-3">
						Click below to copy the exported command string. Store it in a safe place
						to import back onto the site in the future.
					</p>
					<textarea readOnly={true}
						class="form-control mb-3"
						on:click={(event) => {
							event.currentTarget.select()
						}}
						value={ export_snippets($snippets, $command, $commandType) }
					/>
					<Button color="success" on:click={() => { exporting = false }}>
						<CheckCircle />
						Done
					</Button>
				</LightWell>
			</div>
		</Row>
	{:else if colorManaging}
		<!-- <ColorManager customColors={[]}
		setCustomColors={(customColors: Color[]) => { setCustomColors(customColors) }}
		setColorManaging={(newValue: boolean) => { setColorManaging(newValue) }} /> -->
		<ul>
			{#each $customColors as color}
				<li>{color}</li>
			{/each}
		</ul>
	{:else}
		<div class="row">
			<div class="col-sm-8 col-md mb-2">
				<h4>Tellraw Generator for Minecraft</h4>
			</div>
			<div class="col-sm-5 mb-2">
				<div class="btn-toolbar d-flex justify-content-end"
					role="toolbar"
					aria-label="Toolbar with button groups"
				>
					<Button size="sm" color="danger" href="https://github.com/ezfe/tellraw/issues/new" target="_">
						<ExclamationTriangle /> Report an Issue
					</Button>
					<SiteActions />
				</div>
			</div>
		</div>

		{#if !hideWrapper}
			<Row>
				<div class="col-sm-5 col-md-3 mb-2" id="command-label">
					<span style="font-weight: bold;">Command Template</span>
					<br />
					<span>Used to select and execute different players</span>
				</div>
				<div class="col-sm mb-4">
					<input bind:value={$command}
					type="text"
					class="form-control"
					aria-labelledby="command-label" />
				</div>
			</Row>
		{/if}

		<CommandTemplatesController />

		<div class="mb-5">
			<LightWell>
				<SnippetCollection
					snippets={$snippets}
					updateSnippets={(newValue) => {
						snippets.set(newValue)
					}}
					deleteAll={clearAllSnippets}
					bind:commandType={$commandType}
					bind:colorManaging={colorManaging}
					{translationSet}
					bind:hideExteriorWrapper={hideWrapper}
				/>
			</LightWell>
		</div>

		{#if !hideWrapper}
			{#if isFeatureAvailable($commandType, $version, FeatureType.litSign)}
				<div class="row mb-2">
					<div class="col-3">
						<span style="font-weight: bold">Glowing Sign</span>
						<br />
						<span>Illuminate the sign text in dark conditions</span>
					</div>
					<div class="col">
						<input type="checkbox" bind:checked={$litSign} />
					</div>
				</div>
			{/if}
			<div class="row mb-2">
				<div class="col-3">
					<span style="font-weight: bold">Command</span>
					<br />
					<span>Copy and paste into Minecraft</span>
				</div>
				<div class="col">
					<textarea readOnly={true}
					class="form-control"
					onClick={(event) => {
						event.currentTarget.select()
					}}
					value={compiled} />
				</div>
			</div>

			<PreviewContainer snippets={$snippets} commandType={$commandType} {translationSet} />

			<hr />

			<div class="row">
				<div class="col-3">
					<span style="font-weight: bold;">Save and Restore</span>
				</div>
				<div class="col-sm-2 mb-2">
					<Button color="light" block on:click={startImporting}>
						<FileImport /> Import
					</Button>
				</div>
				<div class="col-sm-2 mb-2">
					<Button color="light" block on:click={startExporting}>
						<FileExport /> Export
					</Button>
				</div>
				<div class="col mb-2">
					<span>
						Export your command and save in a text file, so that you can
						get easily get it back. Some browsers reset their cache
						periodically and will forget what you've entered if you don't
						save it by clicking Export.
					</span>
				</div>
			</div>

			<hr />
		{/if}

		<Settings />

		<hr />

		<div class="row">
			<div class="col">
				<span style="color: grey; font-size: 10px;">
					<a href="https://ezekielelin.com/contact" target="_blank">Contact Me</a> | "Minecraft" content and materials are trademarks and copyrights of Mojang and its licensors. This site is not affiliated with Mojang.
				</span>
				<button on:click={speedtest} style="display: none;">speedtest</button>
			</div>
		</div>
	{/if}
</div>

<ArrayDatalist fileIdentifier="keybinds" />
<DictionaryDatalist fileIdentifier="translations" versioned newFileContents={updateTranslationSet} mergeContents={$customLanguageTranslations} />
<ArrayDatalist fileIdentifier="commands" versioned />

<style>
	.container {
		margin-top: 20px;
	}
</style>
