// src/lib/components/generic/Checkbox.svelte
<script type="typescript">
  import { createEventDispatcher } from 'svelte';
  import { v4 as uuidv4 } from 'uuid';


  const dispatch = createEventDispatcher();
  
  export let checked: boolean

  let randomUUID = uuidv4()

  function onChange(event) {
    dispatch('change', event.currentTarget.checked)
  }
  
</script>

<div class="custom-control custom-checkbox">
  <input {checked} on:change={onChange} type="checkbox" class="custom-control-input" id={randomUUID} />
  <label class="custom-control-label" for={randomUUID}><slot /></label>
</div>

// src/components/Forms/Checkbox.tsx
import * as React from "react";
import { v4 as uuidv4 } from 'uuid';

interface CheckboxProps {
  checked: boolean
  onChange: (newValue: boolean) => void
  label: string
}

export const Checkbox: React.FunctionComponent<CheckboxProps> = (props) => {  
  let [randomUUID, setRandomUUID] = React.useState(uuidv4())
  
  return (
    <div className="custom-control custom-checkbox">
      <input checked={props.checked} onChange={event => props.onChange(event.target.checked)} type="checkbox" className="custom-control-input" id={randomUUID} />
      <label className="custom-control-label" htmlFor={randomUUID}>{ props.label }</label>
    </div>  
  )
}
